use_frameworks!
platform :ios, '8.0'

target 'PPScreenshotShare_Example' do
  pod 'PPScreenshotShare', :path => '../'

  target 'PPScreenshotShare_Tests' do
    inherit! :search_paths

    
  end
end
